version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/" # Root directory where your `.gitmodules` file is located
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
