project:
  type: book
  output-dir: output/book/
book:
  title: "Vorlesung Ingenieurinformatik"
  author: 
    - Lukas Arnold
    - Simone Arnold
    - Florian Bagemihl
    - Matthias Baitsch
    - Marc Fehr
    - Maik Poetzsch
    - Sebastian Seipel
  date: today
  language: de-DE
  downloads: [pdf]
  repo-url: "https://github.com/FireDynamics/Vorlesung_Ingenieurinformatik"
  repo-actions: [source]
  favicon: "https://github.com/bausteine-der-datenanalyse/shared-media/blob/main/logo/favicon.svg"
  sidebar:
    title: "Vorlesung Ingenieurinformatik"
    logo: "https://github.com/bausteine-der-datenanalyse/shared-media/blob/main/logo/logo_with_text.svg"
  chapters:
    - index.qmd
format:
  html:
    theme: flatly
    toc: true
    toc-depth: 2
  pdf:
    number-sections: true

execute:
  freeze: auto

