project:
  type: book
  output-dir: output/book/
book:
  title: "Vorlesung Ingenieurinformatik"
  author: 
    - Lukas Arnold
    - Simone Arnold
    - Florian Bagemihl
    - Matthias Baitsch
    - Marc Fehr
    - Maik Poetzsch
    - Sebastian Seipel
  date: today
  language: de-DE
  downloads: [pdf]
  repo-url: "https://github.com/FireDynamics/Vorlesung_Ingenieurinformatik"
  repo-actions: [source]
  favicon: books/shared-media/logo/favicon.svg
  sidebar:
    title: "Vorlesung Ingenieurinformatik"
    logo: books/shared-media/logo/logo_with_text.svg
  chapters:
    - index.qmd
    - part: "Grundlagen Python"
      chapters:
        - books/w-python-minimal/index.qmd
        - books/w-python-minimal/skript/einleitung.qmd
        - books/w-python-minimal/skript/datentypen.qmd
        - books/w-python-minimal/skript/flusskontrolle.qmd
        - books/w-python-minimal/skript/listen_iterationen.qmd 
        - books/w-python-minimal/skript/funktionen.qmd
        - books/w-python-minimal/skript/lesen_schreiben.qmd
    - part: "Matplotlib"
      chapters:
        - books/w-python-matplotlib/index.qmd
        - books/w-python-matplotlib/skript/introduction.qmd
        - books/w-python-matplotlib/skript/basic_plot_types.qmd
        - books/w-python-matplotlib/skript/adapting_plots.qmd
        - books/w-python-matplotlib/skript/advanced_techniques.qmd
        - books/w-python-matplotlib/skript/scientific_plotting.qmd
    - part: "NumPy"
      chapters:
        - books/w-python-numpy-grundlagen/index.qmd
        - books/w-python-numpy-grundlagen/skript/introduction.qmd
        - books/w-python-numpy-grundlagen/skript/array_creation.qmd
        - books/w-python-numpy-grundlagen/skript/array_info.qmd
        - books/w-python-numpy-grundlagen/skript/array_calculation.qmd
        - books/w-python-numpy-grundlagen/skript/array_slicing.qmd
        - books/w-python-numpy-grundlagen/skript/array_manipulation.qmd
        - books/w-python-numpy-grundlagen/skript/array_read_n_write.qmd
        - books/w-python-numpy-grundlagen/skript/array_images.qmd
        - books/w-python-numpy-grundlagen/skript/assessment.qmd
        - books/w-python-numpy-grundlagen/uebungen/uebung.qmd
    - part: "Working with data"
      chapters:
        - books/dataanalysis/introduction.qmd
        - books/dataanalysis/interpolation.qmd
        - books/dataanalysis/fitting.qmd
        - books/dataanalysis/splines.qmd
        - books/dataanalysis/glaetten.qmd        
        - books/dataanalysis/anwendungsbeispiel.qmd
format:
  html:
    toc: true
    toc-depth: 2
  pdf:
    number-sections: true

execute:
  freeze: auto

