# Übersicht {.unnumbered}

## Allgemeine Infos

Die Vorlesung *Ingenieurinformatik* an der Bergischen Universität Wuppertal wurde vom im Jahr 2019 gebildeten Lehrstuhl [Computational Civil Engineering (CCE)](https://cce.uni-wuppertal.de/) übernommen. Der CCE-Lehrstuhl beschäftigt sich hauptsächlich mit der Erforschung und Entwicklung neuer computergestützter Modelle. Im Zentrum der Anwendung steht die numerische Simulation der Brand- und Rauchausbreitung in Gebäuden.  

Da sich das Skript in der Entwicklung befinden freuen wir uns über konstruktive Anregungen und Ihr Feedback. So können Sie Ihre Nachfolger unterstützen.

**Alle organisatorischen Informationen zum Ablauf finden Sie auf der [CCE-Webseite zur Ingenieurinformatik](https://cce.uni-wuppertal.de/index.php?id=4178&L=0).**

## Kontakt

So erreichen Sie uns:
* Als Teilnehmer der Vorlesung: am besten über den zugehörigen [Moodle-Kurs](https://moodle.uni-wuppertal.de/course/view.php?id=46894) an der Bergischen Universität Wuppertal
* Externe Interessenten benutzten am besten unsere <a href="mailto:cce-inginf@lists.uni-wuppertal.de">Emailliste</a>
* Kontaktmöglichkeiten zu einzelnen Personen finden Sie auf der [Mitarbeiterwebseite](https://cce.uni-wuppertal.de/de/team/)


## Abschlussarbeiten

Wir bieten Abschlussarbeiten (BA, MA, PhD) zu vielen verschiedenen Themen an
* eine Themenübersicht und bereits betreuter Arbeiten finden Sie auf der [Webseite der Abschlussarbeiten](https://cce.uni-wuppertal.de/de/abschlussarbeiten/)
* Bei der Themenfindung kann auch die [Übersicht unserer Publikationen](https://www.fz-juelich.de/en/ias/ias-7/profiles/arnold-lukas/journal-articles) helfen
* Bei Interesse kontaktieren Sie bitte Lukas Arnold


## English Version

Is an english version planned? Not yet, please contact Lukas Arnold.